import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutNavbar from "@/components/LayoutNavbar";
import { ThirdwebProviders } from "@/context/ThirdwebProvider";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThirdwebProviders>
      <html lang="en">
        <body className={`${inter.className} bg-[#ECECEC] lg:pt-6 h-full`}>
          <ChakraProvider>
            <LayoutNavbar />
            {children}
          </ChakraProvider>
        </body>
      </html>
    </ThirdwebProviders>
  );
}
