import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutNavbar from "@/components/LayoutNavbar";
import { ThirdwebProviders } from "@/context/ThirdwebProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThirdwebProviders>
      <html lang="en">
        <body className={`${inter.className} bg-zinc-100 pt-6 h-full`}>
          <LayoutNavbar />
          {children}
        </body>
      </html>
    </ThirdwebProviders>
  );
}
